name: DockerHub deploy

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "CI/CD Pipeline" ]
    types:
      - completed
# Environment variables available to all jobs and steps in this workflow
env:
  SPRING_BOOT_IMAGE_NAME: docker-deploy-demo
  SPRING_BOOT_CONTAINER_NAME: spring-boot-deployment-container
  SPRING_BOOT_DEPLOYMENT_NAME: spring-boot-deployment-container

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Checkout main
        uses: actions/checkout@v2


      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #Build the application using Maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      #Build the application using Maven
      - name: Upload JAR
        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
        uses: actions/upload-artifact@v2
        with:
          #Set artifact name
          name: artifact
          #From this path
          path: target/docker-deploy-demo-0.0.1-SNAPSHOT.jar



      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Provide permission to run mvnw
        run: chmod +x ./mvnw

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Spring Boot Image
        id: docker-deploy-demo_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SPRING_BOOT_IMAGE_NAME }}:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}