name: DockerHub deploy

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "CI/CD Pipeline" ]
    types:
      - completed
# Environment variables available to all jobs and steps in this workflow
env:
  SPRING_BOOT_IMAGE_NAME: spring-boot-deployment
  SPRING_BOOT_CONTAINER_NAME: spring-boot-deployment-container
  SPRING_BOOT_DEPLOYMENT_NAME: spring-boot-deployment-container

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main
        uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Provide permission to run mvnw
        run: chmod +x ./mvnw

      - name: Build and push Spring Boot Image
        id: spring-boot-docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SPRING_BOOT_IMAGE_NAME }}:${{ github.sha }}